# Configuración para Railway
[build]
builder = "dockerfile"

# Variables de entorno
[env]
NODE_ENV = "production"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 